config/routes.rb
Rails.application.routes.draw do
  resources :videos

  resources :boards do
    member do
      get 'add' => 'boards#add_video'
      post 'add' => 'boards#map_video'
    end
  end

  root 'videos#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :groupings, dependent: :destroy
  has_many :videos, through: :groupings

  validates :name, presence: true, uniqueness: true
end

app/models/grouping.rb
class Grouping < ActiveRecord::Base
  belongs_to :board
  belongs_to :video

  validates :board_id, :video_id, presence: true

  validates :board_id, uniqueness: {scope: :video_id}
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :groupings, dependent: :destroy
  has_many :boards, through: :groupings

  validates :url, presence: true, uniqueness: true
  validate :youtube_url

  before_save :update_meta_info

  scope :tagged, -> (tags) {where('tags @> ARRAY[?]::varchar[]', [tags].flatten.compact)}

  def self.not_mapped board_id
    joins("LEFT OUTER JOIN (SELECT * FROM groupings WHERE board_id = #{board_id}) g
      ON videos.id = g.video_id WHERE g.video_id IS NULL")
  end

  private

  def youtube_url
    begin
      yt_video.title
    rescue
      errors.add(:url, "could not be processed. Please check if it's a valid YouTube URL.")
    end
  end

  def update_meta_info
    begin
      video = yt_video
      self.title = video.title
      self.description = video.description
      self.tags = video.tags
    rescue
      return false
    end
  end

  def yt_video
    Yt::Video.new url: self.url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy, :add_video, :map_video]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @videos = @board.videos.all
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_video
    @videos = Video.not_mapped @board.id
  end

  def map_video
    @grouping = @board.groupings.new({video_id: params[:video]})
    if @grouping.save
      redirect_to @board, notice: "Video successfully added to your Board."
    else
     redirect_to @board, notice: "We're having some troubles adding the video to the board. Please try again."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    if params[:tag].present?
      @videos = Video.tagged(params[:tag])
    else
      @videos = Video.all
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, notice: "Error processing the URL. Check if it's a valid Youtube URL." }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/videos_helper.rb
module VideosHelper

  def embed_video url
    yt_video(url).embed_html
  end

  def thumbnail_for url
    yt_video(url).thumbnail_url
  end

  def yt_video url
    Yt::Video.new url: url
  end

end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter Board Name", required: "true" %>
  </div>
  <div class="actions">
    <%= f.submit "Done", class: "btn btn-md btn-block btn-info" %>
  </div>
<% end %>

app/views/boards/add_video.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            Add Video to your Board
          </div>
          <div class="panel-body">
            <%= form_tag add_board_path do %>
              <div class="form-group">
                <%= select_tag "video", options_from_collection_for_select(@videos, "id", "title"), class: "form-control" %>
              </div>

              <div class="form-group">
                <%= submit_tag "Save", class: "btn btn-md btn-info" %>
              </div>
            <% end %>
          </div>
          <div class="panel-footer">
            <%= link_to 'Back', videos_path %> |
            <%= link_to 'Video not listed?', new_video_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            Edit Board
          </div>
          <div class="panel-body">
            <%= render 'form' %>
          </div>
          <div class="panel-footer">
            <%= link_to 'Show', @board %> |
            <%= link_to 'Back', boards_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>
    <div class="col-md-8">
      <h1>Your Boards</h1>
    </div>
    <div class="col-md-4 text-right">
      <%= link_to 'New Board', new_board_path, class: 'btn btn-md btn-warning' %>
    </div>

    <div class="col-md-12">
      <% @boards.each do |board| %>
        <div class="col-md-2">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= link_to board.name, board %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            Add New Board
          </div>
          <div class="panel-body">
            <%= render 'form' %>
          </div>
          <div class="panel-footer">
            <%= link_to 'Back', boards_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="jumbotron">
      <p id="notice"><%= notice %></p>

      <p class="lead">
        <%= link_to @board.name, @board %>
      </p>

      <%= link_to 'Edit', edit_board_path(@board) %> |
      <%= link_to 'Delete', @board, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'Add a Video', add_board_path %>
    </div>

    <div class="col-md-12">
      <% @videos.each do |video| %>
        <%= render 'videos/card', video: video %>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pintube</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Pintube", root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Videos", videos_path %></li>
          <li><%= link_to "Boards", boards_path %></li>
        </ul>
      </div>
    </div>
  </nav>

  <%= yield %>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/videos/_card.html.erb
<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= link_to video.title, video %>
    </div>

    <div class="panel-body">
      <div class="col-md-6">
        <%= link_to image_tag(thumbnail_for video.url), video.url, target: "_blank"  %>
      </div>
      <div class="col-md-6">
        <%= truncate(video.description, length: 50) %>
      </div>
    </div>

    <div class="panel-footer">
      <% video.tags.first(2).each do |tag| %>
        | <%= link_to tag, root_path(tag: tag) %>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :url, class: "form-control", placeholder: "Enter the Video URL", required: "true" %>
  </div>
  <div class="actions">
    <%= f.submit "Done", class: "btn btn-md btn-block btn-info" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            Edit Video
          </div>
          <div class="panel-body">
            <%= render 'form' %>
          </div>
          <div class="panel-footer">
            <%= link_to 'Show', @video %> |
            <%= link_to 'Back', videos_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>
    <% if params[:tag].present? %>
      <div class="col-md-12">
        Videos tagged <%= params[:tag] %>
        <%= link_to 'Clear', root_path %>
      </div>
    <% end %>
    <div class="col-md-8">
      <h1>Your Videos</h1>
    </div>
    <div class="col-md-4 text-right">
      <%= link_to 'New Video', new_video_path, class: 'btn btn-md btn-warning' %>
    </div>

    <div class="col-md-12">
      <% @videos.each do |video| %>
        <%= render 'card', video: video %>
      <% end %>

    </div>
  </div>
</div>

app/views/videos/new.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            Add New Video
          </div>
          <div class="panel-body">
            <%= render 'form' %>
          </div>
          <div class="panel-footer">
            <%= link_to 'Back', videos_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="jumbotron">
      <p id="notice"><%= notice %></p>

      <p class="lead">
        <%= link_to @video.title, @video.url, target: "_blank" %>
        <span class="glyphicon glyphicon-new-window"></span>
      </p>

      <%= link_to 'Edit', edit_video_path(@video) %> |
      <%= link_to 'Delete', @video, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>

    <div class="col-md-6 col-md-offset-2">
      <%= raw(embed_video @video.url) %>
    </div>

    <div class="col-md-4">
      <div class="row">
        <%= @video.description %>
      </div>
      <hr />
      <div class="row tags">
        <% @video.tags.each do |tag| %>
          <%= link_to tag, root_path(tag: tag), class: "label label-info" %>
        <% end %>
      </div>
    </div>
  </div>
</div>